### ISSUE TITLE
no such file or directory on Mac

### ISSUE THREAD

**Issue by mosmic** [pamtbaau/angular7-electron3-sqlite3-bootstrap4-webpack4#6]
Hello there and congrats on a really terrific job.

I cloned your repo and followed all the steps. I even set `hasFixedDbLocation = true;` to avoid complexity. I have the following issue though:

ERROR Error: ENOENT: no such file or directory, open '/Users/{myName}/Developer/angular7-electron3-sqlite3-bootstrap4-webpack4/node_modules/electron/dist/Electron.app/Contents/Resources/dist/assets/data/database.db.sql'
    at Object.fs.openSync (fs.js:577)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:166:20)
    at Object.fs.readFileSync (fs.js:483)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:563)
    at Function.createDb (app.js:75040)
    at AppComponent.createDb (app.js:74561)
    at new AppComponent (app.js:74522)
    at createClass (app.js:55847)
    at createDirectiveInstance (app.js:55728)
    at createViewNodes (app.js:56954)
    at createRootView (app.js:56868)
    at callWithDebugContext (app.js:57876)
    at Object.debugCreateRootView [as createRootView] (app.js:57386)
    at 

I'm using a Mac. 

Any chance to know what is going wrong for me?

**Comment by pamtbaau** [comment]
Ouch, doesn't sound nice! Will have a look at it. I don't have a Mac though. I use the poor mans choice...

**Comment by pamtbaau** [comment]
Hm... It works all fine at Windows 10.

I think it is related to line 83 in settings.ts:
```
const isDevMode = /electron/.test(path.basename(remote.app.getPath('exe'), '.exe'));
```

See the docs on [app.getPath('exe')](https://electronjs.org/docs/api/app#appgetpathname).

If I start Electron in dev mode, but force isDevMode to false, I get a similar path as shown in your error. It searches for the database initialisation file in `dist/assets/data/database.db.sql` below node_modules. 

In your case, the correct path should probably be `/Users/{myName}/Developer/angular7-electron3-sqlite3-bootstrap4-webpack4/dist/assets/data/database.db.sql`.

The app uses a pretty simple test to detect if it is running in development mode by using a regex on the path of the 'exe'. This test is only tested for Windows 10. The regex might fail on your Mac if the path returned by `path.basename(remote.app.getPath('exe'), '.exe')` does not contain 'electron'.

Would you mind creating a line above line 82 with `const exePath = path.basename(remote.app.getPath('exe')` '.exe'))` and tell me what the value is?

**Comment by mosmic** [comment]
the value is **Electron**

**Comment by pamtbaau** [comment]
With a capital 'E'?

**Comment by mosmic** [comment]
Yes, I changed the regEx to pass the test and it works fine, but what happens if we do not run in devMode?

is the following path correct then?
Settings.dbFolder = path.join(remote.getGlobal('process').resourcesPath, Settings.dataSubFolder); 

this is what was checking in the node_modules electron directory

**Comment by pamtbaau** [comment]
Pfff, it's a long time ago I wrote that code... 

When Electron is packaged in an `exe`, the `assets/data` files are stored inside the bundle. Then the path to eg. `database.db.sql` should point inside the bundle. That is what `remote.getGlobal('process').resourcesPath` is doing (on Windows). Hope this works on Mac too. Once you `package` this app and install, you will know.... ;-)

**Comment by mosmic** [comment]
Thanks for the support! High quality stuff!

**Comment by pamtbaau** [comment]
Thanks for the compliment (I presume it is...)

Did you change the regex in line 83 to the following to get it working?:
```
const isDevMode = /[eE]lectron/.test(path.basename(remote.app.getPath('exe'), '.exe'));
                   ^^^^
```
If that is working, I can fix the code, publish it and close this issue.

**Comment by mosmic** [comment]
Yes the above fix makes it work.
